services:
  Bazinga\Bundle\GeocoderBundle\DataCollector\GeocoderDataCollector:
    class: Bazinga\Bundle\GeocoderBundle\DataCollector\GeocoderDataCollector
    arguments: ['@Bazinga\Bundle\GeocoderBundle\Logger\GeocoderLogger']
