services:
  Bazinga\Bundle\GeocoderBundle\DataCollector\GeocoderDataCollector:
    class: Bazinga\Bundle\GeocoderBundle\DataCollector\GeocoderDataCollector
    public: false
    tags:
      - { name: data_collector, template: "BazingaGeocoderBundle:Collector:geocoder", id: "geocoder"  }
