on: [push, pull_request]
name: Test
jobs:
    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: PHPStan
              uses: docker://oskarstark/phpstan-ga
              with:
                  args: analyze
    php-cs-fixer:
        name: PHP-CS-Fixer
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: PHP-CS-Fixer
              uses: docker://oskarstark/php-cs-fixer-ga
              with:
                args: --config=.project.php_cs --diff --dry-run
