on: [push]
name: Static analysis
jobs:
    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: PHPStan
              uses: docker://oskarstark/phpstan-ga
              with:
                  args: analyze

    php-cs-fixer:
        name: PHP-CS-Fixer
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: PHP-CS-Fixer
              uses: docker://oskarstark/php-cs-fixer-ga
              with:
                args: --diff --dry-run

    php-cs-fixer_udiff:
        name: PHP-CS-Fixer-udiff
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: PHP-CS-Fixer
              uses: docker://oskarstark/php-cs-fixer-ga
              with:
                args: --dry-run --diff-format udiff

    php-cs-fixer_udiff_diff:
        name: PHP-CS-Fixer-udiff-diff
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: PHP-CS-Fixer
              uses: docker://oskarstark/php-cs-fixer-ga
              with:
                args: --diff --dry-run --diff-format udiff
